### ISSUE TITLE
getting uncaught error event w/ sails and skipper-s3

### ISSUE THREAD

**Issue by mikedevita** [balderdashy/skipper-s3#22] opened 2015-04-04 17:12 UTC
Trying to do file uploads but receiving an error when the file upload kicks off.. 

**The code that im using is..**
I have validated that my connections object has all the right information and that I can push files via the cli to s3 using the same keys. I also validated that the files are being created in `.tmp/s3-upload-part-queue`...

```javascript
      req.file('titleImageLarge').upload({
        adapter: require('skipper-s3'),
        key: sails.config.connections.s3FileStore.key,
        secret: sails.config.connections.s3FileStore.secret,
        bucket: sails.config.connections.s3FileStore.bucket,
      }, function whenDone(err, uploadedFiles){

        if(err) {
          console.log(err);
          return res.send(err);
        }

        res.send(uploadedFiles);
      });
```

**and the error that I am receiving is...**

    events.js:74
            throw TypeError('Uncaught, unspecified "error" event.');
                  ^
    TypeError: Uncaught, unspecified "error" event.
        at TypeError (<anonymous>)
        at Writable.emit (events.js:74:15)
        at /Users/mhdevita/Web/AZ Supras/events/backend/node_modules/skipper-s3/index.js:238:22
        at PassThrough.<anonymous> (/Users/mhdevita/Web/AZ Supras/events/backend/node_modules/skipper-s3/node_modules/knox-mpu-alt/lib/multipartupload.js:328:16)
        at PassThrough.emit (events.js:117:20)
        at /Users/mhdevita/Web/AZ Supras/events/backend/node_modules/sails/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:65:17
        at Function.forEach (/Users/mhdevita/Web/AZ Supras/events/backend/node_modules/sails/node_modules/lodash/dist/lodash.js:3297:15)
        at lodash.ctor.(anonymous function) [as each] (/Users/mhdevita/Web/AZ Supras/events/backend/node_modules/sails/node_modules/lodash/dist/lodash.js:5924:31)
        at Upstream.fatalIncomingError (/Users/mhdevita/Web/AZ Supras/events/backend/node_modules/sails/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:55:18)
        at Writable.unableToUpload (/Users/mhdevita/Web/AZ Supras/events/backend/node_modules/sails/node_modules/skipper/standalone/Upstream/prototype.upload.js:142:10)
        at Writable.g (events.js:180:16)
        at Writable.emit (events.js:117:20)
        at /Users/mhdevita/Web/AZ Supras/events/backend/node_modules/skipper-s3/index.js:238:22
        at /Users/mhdevita/Web/AZ Supras/events/backend/node_modules/skipper-s3/node_modules/knox-mpu-alt/lib/multipartupload.js:217:42
        at /Users/mhdevita/Web/AZ Supras/events/backend/node_modules/skipper-s3/node_modules/knox-mpu-alt/lib/multipartupload.js:131:18
        at Parser.<anonymous> (/Users/mhdevita/Web/AZ Supras/events/backend/node_modules/skipper-s3/node_modules/knox-mpu-alt/node_modules/xml2js/lib/xml2js.js:255:20)

**Comment by ethode-chad** [comment] 2015-04-12 01:46
Well there could be two issues that I have come across working with this.  The first thing you need to check is that the bucket you are calling in the code is the same as the bucket on s3, which was my issue at first, and second you need to make sure that the permissions on that bucket allow everyone to read/write on the folder.  This fixed the exact issue that you are describing with the same stacktrace.  If you go to this directory <code>(/Users/mhdevita/Web/AZ Supras/events/backend/node_modules/skipper-s3/index.js:238:22)</code> and uncomment out the code on line 237 and comment out line 238 it will give you the error in more detail.

**Comment by Dids** [comment] 2015-05-31 13:00
I'm also experiencing this.

@mikedevita Did you ever get this figured out?

**Comment by menacestudio** [comment] 2015-06-01 03:01
I came across the same issue. The way to fix this is to either: a.) make sure that you setup the proper permission on your S3 bucket, and b.) your key, secret and bucket are correct.

Unfortunately, it shuts down the entire server if you encounter this error. It would be great if the library handles this uncaught exception gracefully.

**Comment by igorteton** [comment] 2015-06-01 20:28
I just stumbled onto this problem myself.

I have all permissions and credentials in place but what I am experiencing is that AWS returns:
```
Code: 'TemporaryRedirect',
Message: 'Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.',
```

So it seems that skipper-s3 as a client (or actually knox?) isn't handling redirect on PUT correctly, and I even can't find 'TemporaryRedirect' problem anywhere on knox repo :/

**Comment by Dids** [comment] 2015-06-01 20:32
I ended up having to recreate my bucket using "US Standard" instead of "Oregon" that was selected by default.
There's a ton of issues with most of the NodeJS S3 clients and buckets using regions other than "US Standard", something to do with having to use specific endpoints for every other region.

**Comment by igorteton** [comment] 2015-06-01 20:46
@Dids, You rock!
Recreated it with US Standard and works like a charm.

Also, I dug this official explanation in the meantime: https://forums.aws.amazon.com/message.jspa?messageID=155631#155631.
Yes, I know it's 5 years old, but obviously things haven't changed on that field so I guess it's still relevant source (Which is actually a sad fact!).

**Comment by plato-cambrian** [comment] 2015-06-02 01:07
I am running into this problem **with us-standard AWS region**.

I can't allow this error to kill my application.

Where can I put a try/catch block? I currently have it around one of the asynchronous calls that start `file().upload()` but this obviously doesn't catch the error at some future point in the event loop...

**Comment by Aurelsicoko** [comment] 2015-06-17 09:29
@Dids You rock man ! I just recreate a new bucket using "US Standard" and that works for me !

**Comment by Dids** [comment] 2015-06-17 09:32
@plato-cambrian Try a different S3 client (official AWS SDK is a good start) and you should get a better error message.

For me, if I don't have a bucket using the us-standard region, I have to manually specify the region.
For example, this is how I would do it with the AWS SDK:
```js
AWS.config.update({region: 'eu-central-1'});
```

**Comment by stenio123** [comment] 2015-07-09 02:22
@Dids Thank you so much, you saved my life!!! Changing the bucket region worked!! :-D

**Comment by jettwein** [comment] 2015-07-22 19:56
Ditto. That solved it for me as well. That would have been holy hell to track down - thank you!

**Comment by juanpasolano** [comment] 2015-07-27 21:45
@Dids changing to US Standard.Worked for me too, but I agree with @plato-cambrian this should not kill your application.. That is jus bad. I hope they address this exception.

**Comment by Dids** [comment] 2015-07-27 21:50
@juanpasolano As far as I understand the issue, Skipper/all S3 clients just need to provide, or even force  the use of specifying a region. As long as an S3 client supports setting up a region manually, you don't need the workaround of creating a new bucket in the US Standard region. It's really not that bad, it just feels like most of the maintainers don't know about the issue, with them all/most being US-based developers so they of course default to US Standard.

Hope that makes sense. TL;DR the issue is very, very easy to resolve, and it effects all S3 clients.

**Comment by plato-cambrian** [comment] 2015-07-27 23:33
@dids I still saw this after setting `region: 'us-standard', endpoint: 's3.amazonaws.com'`. It was the same temporary redirect as @igorteton reported

**Comment by Dids** [comment] 2015-07-28 06:13
@plato-cambrian You mean in Skipper? I've tried setting both the region and the endpoint in Skipper, but they didn't seem to effect it, it seems to be hardcoded to only support us-standard buckets. With the AWS SDK though, manually setting the region worked for me, even when using a bucket in the EU.

**Comment by NoRKin** [comment] 2015-08-21 03:00
Had the same issue.

Fixed by adding 
 `region: 'ap-southeast-2',
 endpoint: 's3-ap-southeast-2.amazonaws.com'` (for australia)


@plato-cambrian 
Try `region: us-east-1` instead of us-standard. 
See  http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

There is no `us-standard` according to the above documentation.

**Comment by victorkurauchi** [comment] 2015-09-17 17:24
thank you @Dids  !!!

**Comment by mikermcneil** [comment] 2015-09-18 22:10
Big thanks to @NoRKin and @Dids et. al

**Closed by mikermcneil** 2015-09-18 22:10 UTC
