### ISSUE TITLE
Not working, no error

### ISSUE THREAD

**Issue by eighteyes** [balderdashy/skipper-s3#12] opened 2014-10-08 18:05 UTC
Basically used verbatim from the docs, it won't touch s3 at all. No errors when we change the secret. Where might we look to diagnose this?

**Comment by RSSGergelyMunkacsy** [comment] 2015-01-10 09:18
The same is here...
The tests are failed too with the following error:
```
when some big files start coming in, this adapter should work properly with 2 simultaneous requests with decent-sized (1.5MB) files:
     Error: the string "Unable to initiate stream upload [Invalid upload ID" was thrown, throw an Error :)
      at Runner.fail (/Users/festo/Projects/Research/skipper-s3/node_modules/skipper-adapter-tests/node_modules/mocha/lib/runner.js:197:11)
      at Runner.uncaught (/Users/festo/Projects/Research/skipper-s3/node_modules/skipper-adapter-tests/node_modules/mocha/lib/runner.js:541:8)
      at process.uncaught (/Users/festo/Projects/Research/skipper-s3/node_modules/skipper-adapter-tests/node_modules/mocha/lib/runner.js:568:10)
      at process.emit (events.js:95:17)
      at process._fatalException (node.js:272:26)
```

**Comment by Winangel** [comment] 2015-01-31 16:29
I confirm this issue, setting the skipper-s3 adapter, skipper keep using skipper-disk adapter and files are stored locally...

**Comment by jurajpetrik** [comment] 2015-03-31 15:29
+1.
Is this repository abandoned?

**Comment by jurajpetrik** [comment] 2015-03-31 16:15
I figured it out, skipper-s3 doesn't work for buckets with location in Frankfurt
https://github.com/balderdashy/skipper-s3/issues/21

**Comment by joelanman** [comment] 2015-07-23 15:03
I'm getting this problem. Running on my local machine everything works fine, but on Heroku Skipper fails silently. It runs the 'saveAs' function, but no file ever appears on S3, and final callback with (err, data) doesn't run.

On the same Heroku app, a signed upload direct from the browser works fine.

On some occasions Heroku gives an [H18 error](https://devcenter.heroku.com/articles/error-codes#h18-server-request-interrupted) when using Skipper.

**Comment by sgress454** [comment] 2015-09-18 22:47
Closing as basically a duplicate of #21 and #18.  Basically you need to use a bucket in a region that uses a signature supported by Knox.

**Closed by sgress454** 2015-09-18 22:47 UTC
